crazyflies:
  - channel: 100
    id: 3
    initialPosition: [ 0.0, -5.0, -1.0 ]
    type: default
  - channel: 100
    id: 4
    initialPosition: [ 0.0, -5.0, 0.0 ]
    type: default
  - channel: 100
    id: 8
    initialPosition: [ 0.0, -5.0, 1.0 ]
    type: default